"""add_geometry_to_construction_notices

Revision ID: ebdc06235afa
Revises: 0a7edeccd9e3
Create Date: 2025-11-08 11:34:17.562950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebdc06235afa'
down_revision: Union[str, Sequence[str], None] = '0a7edeccd9e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('construction_notices', sa.Column('geometry', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_road_segments_id'), 'road_segments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_road_segments_id'), table_name='road_segments')
    op.drop_column('construction_notices', 'geometry')
    # ### end Alembic commands ###
